### ISSUE TITLE
Integrate Snapshot API for voting with Holo zk-id on forum

### ISSUE THREAD

**Issue by reneedaos** [reneedaos/Web3-forum-kit#17]
BanklessDeSci is creating a Snapshot space using this documentation: https://medium.com/holonym/sybil-resistant-voting-on-snapshot-5f9b3fdc6680

We will need someone to integrate the Snapshot api using snapshot.js to add both the _create a proposal_ and _cast a vote_ functionality. In version one users will not be able to create or modify spaces from within the forum.

See here: https://docs.snapshot.org/tools/snapshot.js and here: https://github.com/snapshot-labs/snapshot.js

The loop goes like this:
1. Person A creates a proposal (person A selects a button indicating to use Snapshot strategy instead of the zodiac optimistic governance strategy)
2. Persons B, C, etc vote on proposal (let's keep it simple with single choice voting for now, yes, no, abstain)
3. Proposal closes based on date set to close.
4. Decisions are executed off-chain by human decision makers

**Comment by banklesschick** [comment]
This is partially done. Need to finish this code and add the UI elements. https://github.com/banklesschick/upvote-forum/pull/19

**Comment by reneedaos** [comment]
Accomplished by @mzkrasner
